version: "3.9"

services:
  service:
    build:
      context: .
    container_name: worker_service
    env_file:
      - .env
    ports:
      - "8001:8001"
    restart: unless-stopped
    volumes:
      - .:/app